config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :members, except: [:show] do
    collection { post :import }
    member do
      patch :ban
      get :ban
    end
  end

  get 'members/upload', to: 'members#upload', as: 'upload_users'

  get 'posts/report', to: 'members#report', as: 'report'
  get 'limited_report', to: 'members#limited_report', as: 'limited_report'

  resources :posts do
    collection { post :import }
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    conformations: 'users/conformations'
  }
  root 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  include Visible
  validates_presence_of :title
  validates_presence_of :content
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      headers = ['Title', 'Content', 'Comments', 'Likes']
      CSV.generate_line headers
      csv << headers

      all.each do |post|
        csv << [name = "#{post['title']}", "#{post['content']}", post.comments.length, post.likes.length]
      end
    end
  end

  #   def self.to_csv
  #   CSV.generate(headers: true) do |csv|
  #     csv << column_names
  #
  #     all.each do |post|
  #       csv << post.attributes.values_at(*column_names)
  #     end
  #   end
  # end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Post.create! row.to_hash
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
    def demo

    end

    def import
      Post.import(params[:file])
      redirect_to root_url
    end

  def index
    @post = Post.new
    if current_user.roles.first.name == "admin"
    @posts = Post.all
    respond_to do |format|
        format.html
        format.csv { send_data @posts.to_csv }
        format.xlsx
    end

    # @q = Post.ransack(params[:q])
    # @posts = @q.result(distinct: true)
    # respond_to do |format|
    #   format.html
    #   format.csv { send_data @q.result.to_csv }
    # end
    else
      @posts = Post.where(status: :public).or(Post.where(users: current_user))
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :status)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="box" style="background-color: white; border-radius: 15px; padding: 15px;">
  <%= form_with(model: post) do |form| %>
    <div class="d-flex">
      <%= image_tag "icons/Vector.png", style: "padding: 15px" %>
      <div>
        <%= form.text_field :title, value: current_user.name, type: :hidden %>
      </div>
      <div style="margin-top: 5px">
        <%= form.text_field :content, placeholder: "What's happening here?", style: "padding: 15px; border: none; border-radius: 20px; background-color: #F5F6F8; width: 800px" %>
      </div>
    </div>
    <div style="display: flex; gap: 30px; margin-top: 30px;">
      <div style="display: flex; margin-top: 15px;">
        <i class="fa fa-video-camera" style="font-size:18px; padding-top: 5px"></i>
        <p style="margin-left: 10px;">Live Video</p>
      </div>
      <div style="display: flex;  margin-top: 15px">
        <i class="fa fa-picture-o" style="font-size:18px; padding-top: 5px"></i>
        <p style="margin-left: 10px;">Photo/Video</p>
      </div>
      <div style="display: flex;  margin-top: 15px;">
        <i class="fa fa-smile-o" style="font-size:18px; padding-top: 5px"></i>
        <p style="margin-left: 10px;">Smile</p>
      </div>
      <div style="padding-top: 12px">
        <%= form.label :status %>
        <%#= form.select :status, ['public', 'private', 'archived'] %>
        <select name="post[status]" id="post_status" style="border: none; padding: 5px; border-radius: 10px; background-color: #F5F6F8">
          <option value="public">public</option>
          <option value="private">private</option>
          <option value="archived">archived</option>
        </select>
      </div>
      <div style="padding-left: 170px">
        <%= form.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %><br>
    Posted by <%= post.user.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/demo.html.erb
<div class="d-flex justify-content-center">
  <div style="border-radius: 50px; background-color: #FFFFFF; width: 95px; height: 95px; margin-bottom: -40px; z-index: 1;">
    <div style="width: 75px; height: 75px; border-radius: 50px; margin-top: 10px; margin-left: 10px; background-image: linear-gradient(#377DFF, #2DC9EA);">
      <%= image_tag 'photos/report1.png', style: "margin-right: -26px; margin-top: 15px; margin-left: 20px" %>
      <%= image_tag 'photos/report2.png', style: "margin-right: 6px; margin-top: 25px" %>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div style="background-color: #FFFFFF; padding: 50px; border-radius: 20px">
    <h4 class="d-flex justify-content-center">All Users</h4>
    <p class="d-flex justify-content-center">Posts, comments and likes count</p>

    <div class="my-5">
      <form name="forms">
        <div class="d-flex">
          <div style="margin-left: 20px">
            <input type="radio" name="download" value="excel" id="download_excel">
            <label for="download_excel" style="">Excel</label>
          </div>
          <div style="padding-left: 80px">
            <input type="radio" name="download" value="csv" id="download_csv">
            <label for="download_csv" style="">CSV</label>
          </div>
        </div>
        <br>
        <div class="my-5 d-flex justify-content-center">
          <input type="button" value="Download" id="download_btn" class="btn btn-primary px-5 py-2">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= link_to post_path(@post) do %>
  <%= image_tag "photos/back.png", style: "height: 50px; padding: 5px" %>
<% end %>
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%#= link_to post_path(@post) do %>
    <%#= image_tag "photos/back.png", style: "height: 50px; padding: 5px" %>
  <%# end %>
<!--  <%#= link_to "Show this post", @post %> |-->

  <%#= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="mt-3">
  <div class="row mt-2" , style="width: 100vw">
    <div class="col-2">

      <div class="d-flex" , style="margin-left: 20px">
        <%= image_tag "icons/Vector.png", style: "height: 34.3px; width: 32px; margin-right: 10px;" %>
        <h3>Maze</h3>
      </div>

      <div style="padding-top: 40px">
        <div style="margin: 30px auto 20px; margin-left: 30px">
          <%= button_tag class: 'btn btn-primary', style: "padding: 15px 20px;" do %>
          <%= link_to posts_path do %>
            <div class="d-flex " style="height: 15px; padding-left: 20px;">
              <%= image_tag 'photos/feed_icon.png', style: "padding-right: 20px;" %>
              <%= image_tag 'photos/feed_text.png' %>
            </div>
          <% end %>
            <% end %>
        </div>

        <div style="margin: 30px; padding: 20px; padding-top: 30px">
          <%= link_to edit_user_registration_path do %>
            <div class="d-flex " style="height: 15px;">
              <%= image_tag 'icons/profile.png', style: "padding-right: 20px;" %>
              <%= image_tag 'photos/Profile.png' %>
            </div>
          <% end %>
        </div>

        <% if current_user.has_role? :admin %>
          <%= link_to members_path do %>
            <div style="margin: 30px; padding: 20px">
              <div class="d-flex" , style="height: 17px;">
                <%= image_tag 'icons/manage_users.png', style: "padding-right: 20px;" %>
                <%= image_tag 'photos/manage_users.png' %>
              </div>
            </div>
          <% end %>
        <% end %>

        <% if current_user.has_role? :admin %>
          <%= link_to report_path do %>
            <div class="d-flex" style="height: 15px; padding-left: 47px; padding-bottom: 30px">
              <div>
                <%= image_tag 'icons/outside.png', style: "height: 25px;" %>
                <%= image_tag 'icons/inside.png', style: "height: 10px; margin-top: 5px; margin-left: -15px" %>
              </div>
              <div>
                <%= image_tag 'photos/report.png', style: "padding-top: 5px; height: 22px; margin-left: 20px" %>
              </div>
            </div>
          <% end %>
        <% end %>


        <!--      <div>-->
        <%#= link_to "Export posts", posts_path(format: :csv), class: "btn btn-primary btn-lg" %>
        <!--      </div>-->

        <div style="margin: 30px; padding: 20px">
          <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
            <div class="d-flex" , style="height: 15px;">
              <%= image_tag 'icons/logout.png', style: "padding-right: 20px;" %>
              <%= image_tag 'photos/Logout.png' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="container">
        <div class="row" style="margin-bottom: 30px; margin-top: 20px">
          <div class="col-4 d-flex">
            <%= image_tag("icons/Vector.png") %>
            <h3 style="margin-left: 20px; margin-top: 10px;">Maze</h3>
          </div>
          <div class="col-8">
            <div>
              <%= image_tag "icons/Search.png", style: "margin-bottom:-60px; margin-left: 20px;" %>
            </div>
            <div class="form-group" , style="width: 600px">
              <input style="margin-left: 10px; padding-left: 40px; border-radius: 10px;" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Search for something here...">
            </div>
          </div>
          <!--          <div>-->
          <!--            <h3>Import posts</h3>-->
          <%#= form_tag import_posts_path, multipart: true do %>
          <%#= file_field_tag :file %>
          <%#= submit_tag "Import" %>
          <%# end %>
          <!--          </div>-->

          <%#= search_form_for @q, url: :posts do |form| %>
          <!--        <div style="margin: 5px 10px">-->
          <!--          <div class="form-group d-flex">-->
          <%#= form.text_field :title_cont, class: "form-control", placeholder: "Search post by title..." %>
          <%#= form.submit 'Search post', class: "btn btn-primary", style: "margin-left: 5px" %>
          <!--          </div>-->
          <!--        </div>-->
          <%# end %>

        </div>
      </div>
      <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px">
        <%= render 'form', post: @post %>

        <% @posts.to_a.reverse.each do |post| %>
          <div class="box" style="background-color: white; border-radius: 15px; padding: 15px; margin-top: 30px; overflow: scroll">
            <%= link_to post, style: 'text-decoration: none; color: #212529' do %>
              <div class="d-flex">
                <div>
                  <%= image_tag "icons/Vector.png", style: "padding: 15px" %>
                </div>
                <div>
                  <h2 style="padding-top: 10px"><%= post.title %></h2>
                </div>
              </div>
              <strong>Posted by <%= post.user.name %></strong>

              <div class="d-flex">
                <p style="margin-right: 5px">Posted in <%= time_ago_in_words(post.created_at) %>.<%= post.status %></p>
                <p style="margin: 0 10px">.</p>
              </div>
              <div id="text" style="padding: 15px 5px;">
                <p><%= post.content %></p>
              </div>
            <% end %>

            <div id="comment" class="d-flex">
              <p style="margin-right: 5px;"><%= post.likes.count %></p>
              <p>Likes</p>

              <p style="margin: 0 20px; font-weight: bolder">.</p>
              <p><%= pluralize post.comments.count, "Comment" %></p>
            </div>
            <div style="margin: 0 10px">
              <hr>
            </div>
            <div class="d-flex">
              <div class="d-flex">
                <div>
                  <% like = current_user.likes.find_by(likeable: post) %>
                  <% if like.nil? %>
                    <%= button_to likes_path, params: { like: { likeable_id: post.id, likeable_type: Post } }, style: "border: none; background: rgba(113, 190, 52, 0.15); padding: 5px 20px; border-radius: 20px;", method: :post do %>
                      <strong>Like</strong>
                    <% end %>
                  <% else %>
                    <%= button_to like_path(like), style: "border: none; background: rgba(245, 100, 100, 0.15); padding: 5px 20px; border-radius: 20px;", method: :delete do %>
                      <strong>Unlike</strong>
                    <% end %>
                  <% end %>
                </div>
              </div>

              <div class="d-flex" style="margin-left: 300px;">
                <i class="fa fa-commenting-o" aria-hidden="true" style="padding-top: 5px;"></i>
                <%= link_to "Comment", post, style: "text-decoration: none; color: black; margin-left: 10px;" %>
              </div>
            </div>
            <div style="margin: 0 10px 0 5px;">
              <hr>
            </div>

            <%= render 'comments/form', post: post %>

            <hr>

          </div>
        <% end %>

      </div>
    </div>
    <div class="col-2" , style="padding: 10px">
      <div class="d-flex">
        <%= image_tag "photos/admin.jpg", style: "border-radius: 300px; height: 50px" %>
        <div>
          <span style="font-size: 20px; margin-left: 15px"><%= current_user.name %></span>
          <p style="margin-left: 20px"><%= current_user.roles.pluck(:name).join(",").capitalize %></p>
        </div>
      </div>
      <br>


      <% if current_user.has_role? :admin %>
        <div class="d-flex">
          <p style="padding-top: 2px; padding-right: 120px">Users List</p>
          <%= image_tag "photos/dots.png", style: "height: 30px" %>
        </div>

        <div>
          <% @users = User.all %>
          <% @users.each do |user| %>
            <% if user.posts.any? %>
              <div class="d-flex">
                <div style="background-color: #F5F6F8; margin: 20px 10px; padding: 5px; border-radius: 30px">
                  <%= image_tag "icons/Vector.png" %>
                </div>
                <strong style="padding-top: 30px; color: #9FA0A3;"><%= user.name %></strong>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div style="height: 100vh">
  <%= link_to posts_path do %>
    <%= image_tag "photos/back.png", style: "height: 50px; padding: 5px" %>
  <% end %>

  <div class="container" style="margin-top: 20px">
    <div class="row" style="margin-bottom: 30px">
      <div class="col-4 d-flex">
        <%= image_tag("icons/Vector.png") %>
        <h3 style="margin-left: 20px; margin-top: 10px;">Maze</h3>
      </div>
      <div class="col-8">
        <div>
          <%= image_tag "icons/Search.png", style: "margin-bottom:-60px; margin-left: 20px;" %>
        </div>
        <div class="form-group">
          <input style="margin-left: 10px; padding-left: 40px; border-radius: 10px" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Search for something here...">
        </div>
      </div>
    </div>
  </div>

  <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px;">
    <div class="box" style="background-color: white; border-radius: 15px; padding: 15px; margin-top: 10px;">
      <div class="d-flex">
        <%= image_tag "icons/Vector.png", style: "padding: 15px" %>
        <h2 style="width: 1050px"><%= @post.title %></h2>

        <% if @post.user == current_user || (current_user.has_role? :admin) %>
          <div>
            <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-primary", type: "submit", style: "border-radius: 10px; margin: 5px 10px;" %>
          </div>
          <div>
            <%= button_to "Delete", @post, method: :delete, class: "btn btn-outline-danger", type: "submit", style: "border-radius: 10px; margin: 5px 10px;" %>
          </div>
        <% end %>
      </div>
      <div id="text" style="padding: 15px 5px;">
        <p><%= @post.content %></p>
      </div>
      <div id="comment" class="d-flex">
        <p style="margin-right: 5px;"><%= @post.likes.count %></p>
        <p>Likes</p>
        <p style="margin: 0 20px; font-weight: bolder">.</p>
        <p><%= pluralize @post.comments.count, "Comment" %></p>
      </div>
      <div style="margin: 0 10px">
        <hr>
      </div>
      <div class="d-flex">
        <div class="d-flex">
          <div>
            <% like = current_user.likes.find_by(likeable: @post) %>
            <% if like.nil? %>
              <%= button_to likes_path, params: { like: { likeable_id: @post.id, likeable_type: Post } }, style: "border: none; background: rgba(113, 190, 52, 0.15); padding: 5px 20px; border-radius: 20px;", method: :post do %>
                <strong>Like</strong>
              <% end %>
            <% else %>
              <%= button_to like_path(like), style: "border: none; background: rgba(245, 100, 100, 0.15); padding: 5px 20px; border-radius: 20px;", method: :delete do %>
                <strong>Unlike</strong>
              <% end %>
            <% end %>
          </div>

        </div>
        <div class="d-flex" style="margin-left: 300px;">
          <i class="fa fa-commenting-o" aria-hidden="true" style="padding-top: 5px;"></i>
          <p style="margin-left: 20px">Comments</p>
        </div>
      </div>
      <div style="margin: 0 10px 0 5px;">
        <hr>
      </div>

      <%= render 'comments/form', post: @post %>
      <div style="margin-top: 30px; margin-left: 10px">Comments</div>
      <div style="margin: 10px">
        <hr>
      </div>

      <% @comments.each do |comment| %>
        <div class="d-flex" style="margin-left: 10px;">
          <!--        <div style="width: 1100px"><%#= comment.content  %></div>-->
          <%= render 'comments/comment', post: @post, comment: comment %>
          <!--        <div class="d-flex">-->
          <!--          <i class="fa fa-heart-o" aria-hidden="true" style="padding-top: 5px; margin-left: 20px"></i>-->
          <!--          <i class="fa fa-trash-o" aria-hidden="true" style="padding-top: 5px; margin-left: 20px"></i>-->
          <!--          <i class="fa fa-pencil" aria-hidden="true" style="padding-top: 5px; margin-left: 20px"></i>-->
          <!--        </div>-->
        </div>
        <div style="margin: 10px">
          <hr>
        </div>
      <% end %>

    </div>
  </div>
</div>