config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :members, except: [:show] do
    collection { post :import }
    member do
      patch :ban
      get :ban
    end
  end

  get 'members/upload', to: 'members#upload', as: 'upload_users'

  get 'posts/report', to: 'members#report', as: 'report'
  get 'limited_report', to: 'members#limited_report', as: 'limited_report'

  resources :posts do
    collection { post :import }
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    conformations: 'users/conformations'
  }
  root 'home#index'
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!


  def upload

  end

  def import
    TaskLoggerJob.perform_now(params[:file])
    # UserMailer.with(user: @user).welcome_email.deliver_later
    redirect_to members_path #, flash[:notice] =  "Posts has been imported successfully."
  end

  def index
    if current_user.roles.first.name == "admin"
      @users = User.order(created_at: :desc)
      respond_to do |format|
        format.html
        format.csv { send_data @users.to_csv }
        format.xlsx
      end
    else
      redirect_to posts_path
    end
  end

  def limited_report
    @users = User.all

    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv_limited }
    end
  end

  def edit
    if current_user.roles.first.name == "admin"
      @user = User.find(params[:id])
    else
      redirect_to posts_path
    end
  end

  def new
    if current_user.roles.first.name == "admin"
      @user = User.new
    else

      redirect_to posts_path
    end
  end

  def create
    if current_user.roles.first.name == "admin"
      @user = User.new(user_params)
      @user.add_role params[:roles]
      if @user.save!
        UserMailer.with(user: @user).welcome_email.deliver_now
        redirect_to posts_path
      else
        redirect_to new
      end
    else
      redirect_to posts_path
    end
  end

  def ban
    if current_user.roles.first.name == "admin"
      @user = User.find(params[:id])
      if @user.access_locked?
        @user.unlock_access!
      else
        @user.lock_access!
      end
      redirect_to members_path
    else
      redirect_to posts_path
    end
  end

  private

  def user_params
    params.permit(:name, :lname, :email, :number, :password, :password_confirmation)
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def ban_status(user)
    if user.access_locked?
      "Activate"
    else
      "Deactivate"
    end
  end
end

app/views/members/edit.html.erb
<h1 class="d-flex justify-content-center">Edit user role</h1>

app/views/members/index.html.erb
<%#= link_to 'Download as .xlsx', members_path(format: :xlsx) %>
<%#=
<!--  link_to 'Download as Excel',-->
<!--          members_path(format: :xlsx)-->
%>

<div class="row mt-3" style="width: 100vw">
  <div class="col-2">
    <div class="d-flex" , style="margin-left: 20px">
      <%= image_tag "icons/Vector.png", style: "height: 34.3px; width: 32px; margin-right: 10px;" %>
      <h3>Maze</h3>
    </div>

    <div style="padding-top: 40px">
      <div style="margin: 30px auto 20px; margin-left: 30px">
        <%= link_to posts_path do %>
          <div class="d-flex " style="height: 15px; padding-left: 20px;">
            <%= image_tag 'icons/feed.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/feed.png' %>
          </div>
        <% end %>
      </div>

      <div style="margin: 30px 0px 30px 30px; padding: 20px">
        <%= link_to edit_user_registration_path do %>
          <div class="d-flex " , style="height: 15px;">
            <%= image_tag 'icons/profile.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Profile.png' %>
          </div>
        <% end %>
      </div>

      <%= button_tag class: "btn btn-primary", style: "margin-left: 30px; margin-bottom: 30px" do %>
        <%= link_to members_path do %>
          <div>
            <div class="d-flex" , style="height: 17px; margin: 10px 0px;">
              <%= image_tag 'photos/manage_icon.png', style: "padding-right: 20px;" %>
              <%= image_tag 'photos/manage_text.png' %>
            </div>
          </div>
        <% end %>
      <% end %>

      <!--    <div>-->
      <%#= link_to "Export posts", posts_path(format: :csv), class: "btn btn-primary btn-lg" %>
      <!--    </div>-->

      <!--    <div>-->
      <%#= link_to "Export users", members_path(format: :csv), class: "btn btn-primary btn-lg" %>
      <!--    </div>-->

      <% if current_user.has_role? :admin %>
        <%= link_to report_path do %>
          <div class="d-flex" style="height: 15px; padding-left: 47px; padding-bottom: 30px">
            <div>
              <%= image_tag 'icons/outside.png', style: "height: 25px;" %>
              <%= image_tag 'icons/inside.png', style: "height: 10px; margin-top: 5px; margin-left: -15px" %>
            </div>
            <div>
              <%= image_tag 'photos/report.png', style: "padding-top: 5px; height: 22px; margin-left: 20px" %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div style="margin: 30px; padding: 20px">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
          <div class="d-flex" , style="height: 15px;">
            <%= image_tag 'icons/logout.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Logout.png' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-10">
    <div class="container">
      <div class="d-flex">
        <p style="font-size: 25px; font-weight: bold; color: #9FA0A3;">User Management</p>
        <div class="d-flex" , style="padding-left: 700px">
          <%= image_tag "photos/admin.jpg", style: "border-radius: 300px; height: 50px" %>
          <div>
            <span style="font-size: 20px; margin-left: 15px"><%= current_user.name %></span>
            <p style="margin-left: 20px"><%= current_user.roles.pluck(:name).join(",").capitalize %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px">


      <div class="d-flex">
        <strong style="font-size: 25px">List of Users</strong>

        <div style="margin-left: 600px; border-radius: 20px; background: white; padding: 10px 10px 5px 10px; ">
          <%= link_to upload_users_path do %>
            <%= image_tag 'photos/upload.png' %><span style="margin-left: 15px">Upload users</span>
          <% end %>
        </div>

        <div style="margin-left: 30px">
          <%= link_to new_member_path do %>
            <%= button_tag class: 'btn btn-primary', style: "border-radius: 20px; padding: 5px 15px; " do %>
              <%= image_tag 'icons/create.png' %><span style="font-size: 20px; margin-left: 15px">Create Users</span>
            <% end %>
          <% end %>
        </div>
      </div>


      <div class="row" , style="overflow: scroll">
        <% @users.each do |user| %>
          <% if !(user.has_role? :admin) %>
            <div class="d-flex" , style="background-color: #FFFFFF; padding: 10px; margin: 20px 0px; border-radius: 10px">
              <div class="col-2">
                <div>
                  <%= image_tag "icons/Vector.png", style: "background-color: #F5F6F8; padding: 5px; border-radius: 30px" %>
                </div>
              </div>
              <strong class="col-2" style="font-size: 20px; color: #9FA0A3;  padding-top: 5px;">
                <%= user.name %>
              </strong>

              <strong class="col-2" , style="padding-top: 10px; color: #9FA0A3;">
                <%= user.number %>
              </strong>

              <strong class="col-2" , style="padding-top: 10px; color: #9FA0A3;">
                <%= user.email %>
              </strong>

              <div class="col-2" style="padding-left: 80px; padding-top: 10px;">
                <% if ban_status(user) == "Activate" %>
                  <%= link_to ban_status(user), ban_member_path(user), method: :patch, style: "text-decoration: none; background: rgba(113, 190, 52, 0.15); padding: 10px 40px; border-radius: 20px; color: #71BE34; font-weight: 600;" %>
                <% else %>
                  <%= link_to ban_status(user), ban_member_path(user), method: :patch, style: "text-decoration: none; background: rgba(245, 100, 100, 0.15); padding: 10px 40px; border-radius: 20px; color: #F56464; font-weight: 600;" %>
                <% end %>
              </div>
              <div class="col-2" , style="padding-top: 5px; padding-left: 150px;">
                <%= image_tag "photos/dots.png", style: "height: 30px" %>
              </div>
            </div>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/new.html.erb
<div class="row" , style="width: 100vw">
  <div class="col-2">
    <div class="d-flex" , style="margin-left: 20px">
      <%= image_tag "icons/Vector.png", style: "height: 34.3px; width: 32px; margin-right: 10px;" %>
      <h3>Maze</h3>
    </div>

    <div style="margin: 30px auto 20px; margin-left: 30px">
      <%= link_to posts_path do %>
        <%= button_tag class: 'btn btn-primary', style: "width: 150px; padding: 10px" do %>
          <%= image_tag 'icons/feed.png', style: "margin-right: 10px" %><span style="font-size: 20px">Feed</span>
        <% end %>
      <% end %>
    </div>

    <div style="margin: 30px; padding: 20px">
      <%= link_to edit_user_registration_path do %>
        <div class="d-flex " , style="height: 15px;">
          <%= image_tag 'icons/profile.png', style: "padding-right: 20px;" %>
          <%= image_tag 'photos/Profile.png' %>
        </div>
      <% end %>
    </div>

    <%= link_to members_path do %>
      <div style="margin: 30px; padding: 20px">
        <div class="d-flex" , style="height: 17px;">
          <%= image_tag 'icons/manage_users.png', style: "padding-right: 20px;" %>
          <%= image_tag 'photos/manage_users.png' %>
        </div>
      </div>
    <% end %>


    <div style="margin: 30px; padding: 20px">
      <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
        <div class="d-flex" , style="height: 15px;">
          <%= image_tag 'icons/logout.png', style: "padding-right: 20px;" %>
          <%= image_tag 'photos/Logout.png' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-10">
    <div class="container">
      <div class="d-flex">
        <p style="font-size: 25px; font-weight: bold; color: #9FA0A3;">User Management</p>
        <div class="d-flex" , style="padding-left: 700px">
          <%= image_tag "photos/admin.jpg", style: "border-radius: 300px; height: 50px" %>
          <div>
            <span style="font-size: 20px; margin-left: 15px"><%= current_user.name %></span>
            <p style="margin-left: 20px"><%= current_user.roles.pluck(:name).join(",").capitalize %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px">

        <strong style="font-size: 25px">Add User</strong>

      <%= form_with url: '/members', method: :post do |f| %>


      <div class="row">
        <div class="col-6">
          <%= f.text_field :name, class: 'form-control form-control-lg', placeholder: 'First name', style: "border-radius: 15px; margin: 40px 0px;" %>
          <%= f.email_field :email, class: 'form-control form-control-lg', placeholder: 'Email id', style: "border-radius: 15px; margin: 40px 0px;" %>
          <%= f.password_field :password, class: 'form-control form-control-lg', placeholder: 'Choose password', style: "border-radius: 15px; margin: 40px 0px;" %>
        </div>

        <div class="col-6">
          <%= f.text_field :lname, class: 'form-control form-control-lg', placeholder: 'Last name', style: "border-radius: 15px; margin: 40px 0px;" %>
          <%= f.text_field :number, class: 'form-control form-control-lg', placeholder: 'Mobile number.', style: "border-radius: 15px; margin: 40px 0px;", maxlength: "10", size: "10"  %>
          <%= f.password_field :password_confirmation, class: 'form-control form-control-lg', placeholder: 'Confirm password', style: "border-radius: 15px; margin: 40px 0px;" %>
        </div>
      </div>
        <br>
        <div>
          Assign role
        <%= f.radio_button :roles, 'Role1' %>
        <%= f.label :Role1, 'Role-1' %>

          <%= f.radio_button :roles, 'Role2' %>
          <%= f.label :Role2, 'Role-2' %>


        </div>
        <%= f.submit 'Create user', class: "btn btn-outline-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/members/report.html.erb
<div class="row mt-3" style="width: 100vw">
  <div class="col-2">
    <div class="d-flex" , style="margin-left: 20px">
      <%= image_tag "icons/Vector.png", style: "height: 34.3px; width: 32px; margin-right: 10px;" %>
      <h3>Maze</h3>
    </div>

    <div style="padding-top: 40px">
      <div style="margin: 30px auto 20px; margin-left: 30px">
        <%= link_to posts_path do %>
          <div class="d-flex " style="height: 15px; padding-left: 20px;">
            <%= image_tag 'icons/feed.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/feed.png' %>
          </div>
        <% end %>
      </div>

      <div style="margin: 30px; padding: 20px">
        <%= link_to edit_user_registration_path do %>
          <div class="d-flex " , style="height: 15px;">
            <%= image_tag 'icons/profile.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Profile.png' %>
          </div>
        <% end %>
      </div>

      <%= link_to members_path do %>
        <div style="margin: 30px; padding: 20px">
          <div class="d-flex" , style="height: 17px;">
            <%= image_tag 'icons/manage_users.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/manage_users.png' %>
          </div>
        </div>
      <% end %>

      <% if current_user.has_role? :admin %>
        <div style="padding-left: 35px">
          <%= button_tag class: "btn btn-primary" do %>
            <%= link_to report_path do %>
              <div class="d-flex" style="height: 15px; padding-bottom: 30px">
                <div>
                  <%= image_tag 'photos/report_outside.png', style: "height: 25px;" %>
                  <%= image_tag 'photos/report_inside.png', style: "height: 10px; margin-top: 5px; margin-left: -15px" %>
                </div>
                <div>
                  <%= image_tag 'photos/report_text.png', style: "padding-top: 5px; height: 22px; margin-left: 20px" %>
                </div>
              </div>
            <% end %>
          <% end %>
      <% end %>
      </div>


      <div style="margin: 30px; padding: 20px">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
          <div class="d-flex" style="height: 15px;">
            <%= image_tag 'icons/logout.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Logout.png' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-10">
    <div class="container">
      <div class="d-flex">
        <div class="d-flex" , style="border: 1px solid rgba(51, 51, 51, 0.3); height: 50px; padding: 10px; border-radius: 10px; width: 900px" ,>
          <div>
            <%= image_tag 'icons/search.png', style: "margin-right: 20px " %>
          </div>
          <div>Search something for here...</div>
        </div>
        <div class="d-flex" , style="padding-left: 100px">
          <%= image_tag "photos/admin.jpg", style: "border-radius: 300px; height: 50px" %>
          <div>
            <span style="font-size: 20px; margin-left: 15px"><%= current_user.name %></span>
            <p style="margin-left: 20px"><%= current_user.roles.pluck(:name).join(",").capitalize %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px">

      <div class="d-flex">
        <div style="margin-right: 50px;">
          <div class="d-flex justify-content-center">
            <div style="border-radius: 50px; background-color: #FFFFFF; width: 95px; height: 95px; margin-bottom: -40px; z-index: 1;">
              <div style="width: 75px; height: 75px; border-radius: 50px; margin-top: 10px; margin-left: 10px; background-image: linear-gradient(#377DFF, #2DC9EA);">
                <%= image_tag 'photos/report1.png', style: "margin-right: -26px; margin-top: 15px; margin-left: 22px" %>
                <%= image_tag 'photos/report2.png', style: "margin-right: 6px; margin-top: 25px" %>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-center">
            <div style="background-color: #FFFFFF; padding: 50px; border-radius: 20px">
              <h4 class="d-flex justify-content-center">All Users</h4>
              <p class="d-flex justify-content-center" , style="color: #9FA0A3">Posts, comments and likes count</p>

              <div class="my-5">
                <form name="forms">
                  <div class="d-flex">
                    <div style="margin-left: 20px">
                      <input type="radio" name="download" value="excel" id="download_excel">
                      <label for="download_excel" style="">Excel</label>
                    </div>
                    <div style="padding-left: 80px">
                      <input type="radio" name="download" value="csv" id="download_csv" checked>
                      <label for="download_csv" style="">CSV</label>
                    </div>
                  </div>
                  <br>
                  <div class="my-5 d-flex justify-content-center">
                    <input type="button" value="Download" id="download_btn" class="btn btn-primary px-5 py-2">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div style="margin-right: 50px;">
          <div class="d-flex justify-content-center">
            <div style="border-radius: 50px; background-color: #FFFFFF; width: 95px; height: 95px; margin-bottom: -40px; z-index: 1;">
              <div style="width: 75px; height: 75px; border-radius: 50px; margin-top: 10px; margin-left: 10px; background-image: linear-gradient(#377DFF, #2DC9EA);">
                <%= image_tag 'photos/report1.png', style: "margin-right: -26px; margin-top: 15px; margin-left: 22px" %>
                <%= image_tag 'photos/report2.png', style: "margin-right: 6px; margin-top: 25px" %>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-center">
            <div style="background-color: #FFFFFF; padding: 50px; border-radius: 20px">
              <h4 class="d-flex justify-content-center">All Users</h4>
              <p class="d-flex justify-content-center" , style="color: #9FA0A3">Having more than 10 posts, users</p>

              <div class="my-5">
                <form name="forms">
                  <div class="d-flex">
                    <div style="margin-left: 20px">
                      <input type="radio" name="download" value="excel" id="limited_excel">
                      <label for="limited_excel" style="">Excel</label>
                    </div>
                    <div style="padding-left: 80px">
                      <input type="radio" name="download" value="csv" id="limited_csv" checked>
                      <label for="limited_csv" style="">CSV</label>
                    </div>
                  </div>
                  <br>
                  <div class="my-5 d-flex justify-content-center">
                    <input type="button" value="Download" id="limited_btn" class="btn btn-primary px-5 py-2">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div class="d-flex justify-content-center">
            <div style="border-radius: 50px; background-color: #FFFFFF; width: 95px; height: 95px; margin-bottom: -40px; z-index: 1;">
              <div style="width: 75px; height: 75px; border-radius: 50px; margin-top: 10px; margin-left: 10px; background-image: linear-gradient(#377DFF, #2DC9EA);">
                <%= image_tag 'photos/report1.png', style: "margin-right: -26px; margin-top: 15px; margin-left: 22px" %>
                <%= image_tag 'photos/report2.png', style: "margin-right: 6px; margin-top: 25px" %>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-center">
            <div style="background-color: #FFFFFF; padding: 50px; border-radius: 20px">
              <h4 class="d-flex justify-content-center">Post-wise reports</h4>
              <p class="d-flex justify-content-center" , style="color: #9FA0A3">Title/description, comments, likes</p>

              <div class="my-5">
                <form name="forms">
                  <div class="d-flex">
                    <div style="margin-left: 20px">
                      <input type="radio" name="download" value="excel" id="post_excel">
                      <label for="post_excel" style="">Excel</label>
                    </div>
                    <div style="padding-left: 80px">
                      <input type="radio" name="download" value="csv" id="post_csv" checked>
                      <label for="post_csv" style="">CSV</label>
                    </div>
                  </div>
                  <br>
                  <div class="my-5 d-flex justify-content-center">
                    <input type="button" value="Download" id="post_btn" class="btn btn-primary px-5 py-2">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

<script>
    let xls = document.getElementById('download_excel')
    let csv = document.getElementById('download_csv')
    let btn = document.getElementById('download_btn')
    let errorMsgUser = document.getElementById('msg_user')

    btn.onclick = myFunction

    function myFunction() {
        if (xls.checked) {
            open('/members.xlsx');
        } else {
            open('/members.csv')
        }
    }
</script>

<script>
    let xlsLimited = document.getElementById('limited_excel')
    let csvLimited = document.getElementById('limited_csv')
    let btnLimited = document.getElementById('limited_btn')
    let errorMsgLimit = document.getElementById('msg_limit')

    btnLimited.onclick = myFunction

    function myFunction() {
        if (xlsLimited.checked) {
            open('/limited_report.xlsx');
        } else {
            open('/limited_report.csv')
        }
    }
</script>

<script>
    let xlsPost = document.getElementById('post_excel')
    let csvPost = document.getElementById('post_csv')
    let btnPost = document.getElementById('post_btn')
    let errorMsgPost = document.getElementById('msg_post')

    btnPost.onclick = myFunction

    function myFunction() {
        if (xlsPost.checked) {
            open('/posts.xlsx');
        } else {
            open('/posts.csv')
        }
    }
</script>

app/views/members/upload.html.erb
<div class="row mt-3" style="width: 100vw">
  <div class="col-2">
    <div class="d-flex" , style="margin-left: 20px">
      <%= image_tag "icons/Vector.png", style: "height: 34.3px; width: 32px; margin-right: 10px;" %>
      <h3>Maze</h3>
    </div>

    <div style="padding-top: 40px">
      <div style="margin: 30px auto 20px; margin-left: 30px">
        <%= link_to posts_path do %>
          <div class="d-flex " style="height: 15px; padding-left: 20px;">
            <%= image_tag 'icons/feed.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/feed.png' %>
          </div>
        <% end %>
      </div>

      <div style="margin: 30px; padding: 20px">
        <%= link_to edit_user_registration_path do %>
          <div class="d-flex " , style="height: 15px;">
            <%= image_tag 'icons/profile.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Profile.png' %>
          </div>
        <% end %>
      </div>

      <%= link_to members_path do %>
        <div style="margin: 30px; padding: 20px">
          <div class="d-flex" , style="height: 17px;">
            <%= image_tag 'icons/manage_users.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/manage_users.png' %>
          </div>
        </div>
      <% end %>

      <!--    <div>-->
      <%#= link_to "Export posts", posts_path(format: :csv), class: "btn btn-primary btn-lg" %>
      <!--    </div>-->

      <!--    <div>-->
      <%#= link_to "Export users", members_path(format: :csv), class: "btn btn-primary btn-lg" %>
      <!--    </div>-->

      <% if current_user.has_role? :admin %>
        <%= link_to report_path do %>
          <div class="d-flex" style="height: 15px; padding-left: 47px; padding-bottom: 30px">
            <div>
              <%= image_tag 'icons/outside.png', style: "height: 25px;" %>
              <%= image_tag 'icons/inside.png', style: "height: 10px; margin-top: 5px; margin-left: -15px" %>
            </div>
            <div>
              <%= image_tag 'photos/report.png', style: "padding-top: 5px; height: 22px; margin-left: 20px" %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div style="margin: 30px; padding: 20px">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
          <div class="d-flex" , style="height: 15px;">
            <%= image_tag 'icons/logout.png', style: "padding-right: 20px;" %>
            <%= image_tag 'photos/Logout.png' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-10">
    <div class="container">
      <div class="d-flex">
        <div class="d-flex" , style="border: 1px solid rgba(51, 51, 51, 0.3); height: 50px; padding: 10px; border-radius: 10px; width: 900px" ,>
          <div>
            <%= image_tag 'icons/search.png', style: "margin-right: 20px " %>
          </div>
          <div>Search something for here...</div>
        </div>
        <div class="d-flex" , style="padding-left: 100px">
          <%= image_tag "photos/admin.jpg", style: "border-radius: 300px; height: 50px" %>
          <div>
            <span style="font-size: 20px; margin-left: 15px"><%= current_user.name %></span>
            <p style="margin-left: 20px"><%= current_user.roles.pluck(:name).join(",").capitalize %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background-color: #F5F6F8; padding: 30px; border-radius: 20px; margin-bottom: 20px">

      <%= form_tag import_members_path, multipart: true do %>

        <%= submit_tag "Import" %>

        <div style="border: 2px solid grey; height: 400px; width: 800px; background-color: white; border-radius: 10px; margin-top: 60px; margin-left: 170px; margin-bottom: 30px">
          <h4 style="margin-top: 20px; margin-left: 20px;">Upload file</h4>
          <div style="margin-left: 170px; margin-top: 120px;">
            <%= file_field_tag :file, style: "width: 420px; height: 100px; opacity: 0;", accept: ".xlsx" %>
            <div style="margin-top: -100px">
              <%= image_tag 'photos/upload_bc.png' %>
              <%= image_tag 'photos/upload1.png', style: "margin-left: -425px;" %>
              <%= image_tag 'photos/upload2.png', style: "margin-left: -75px; margin-top: 25px;" %>
              <%= image_tag 'photos/uploadtext.png', style: "margin-left: 100px;" %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>